services:
  server:
    build:
      context: ../scripts
      dockerfile: ../openvpn-openvpn-tcp/Dockerfile
    container_name: openvpn-tcp-server
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - ./keys:/app/keys
    ports:
      - "443:443/tcp"
    command: "sh -e -x /app/server.sh 443 tcp"

  client:
    build:
      context: ../scripts
      dockerfile: ../openvpn-openvpn-tcp/Dockerfile
    container_name: openvpn-tcp-client
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - ./keys:/app/keys
      - ./result:/app/log
      - ../data:/app/data
    environment:
      - SOFTWARE=openvpn-tcp
      - DATA_PATH=/app/data/big_data.json
      - LOG_PATH=/app/log
    depends_on:
      - server
    command: "sh -e -x /app/connect.sh 443 tcp"
