services:
  server:
    build:
      context: ../scripts
      dockerfile: ../wireguard-linux/Dockerfile
    container_name: wireguard-linux-server
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - ./keys:/app/keys
    ports:
      - "51820:51820/udp"
    command: "sh -e -x /app/server.sh"

  client:
    build:
      context: ../scripts
      dockerfile: ../wireguard-linux/Dockerfile
    container_name: wireguard-linux-client
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - ./keys:/app/keys
      - ./result:/app/log
      - ../data:/app/data
    environment:
      - SOFTWARE=wireguard-linux
      - DATA_PATH=/app/data/big_data.json
      - LOG_PATH=/app/log
    depends_on:
      - server
    command: "sh -e -x /app/connect.sh"
