services:
  server:
    build:
      context: ../scripts
      dockerfile: ../openvpn-openvpn-udp/Dockerfile
    container_name: openvpn-udp-server
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - ./keys:/app/keys
    ports:
      - "1194:1194/udp"
    command: "sh -e -x /app/server.sh 1194 udp"

  client:
    build:
      context: ../scripts
      dockerfile: ../openvpn-openvpn-udp/Dockerfile
    container_name: openvpn-udp-client
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - ./keys:/app/keys
      - ./result:/app/log
      - ../data:/app/data
    environment:
      - SOFTWARE=openvpn-udp
      - DATA_PATH=/app/data/big_data.json
      - LOG_PATH=/app/log
    depends_on:
      - server
    command: "sh -e -x /app/connect.sh 1194 udp"
